### ISSUE TITLE
Multiple packages found with the same name "uml_hri_nerve_pick_and_place"

### ISSUE THREAD

**Issue by decdox** [kyassini/manipulation_experiments#1]
i put the two packages (armada_manipulation_old and manipulation_experiments) under the same workspace, it turns out the following error info. how to build it, thx!

Traceback (most recent call last):
  File "/usr/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.6.1', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 272, in main
    catkin_main(sysargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 422, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 283, in build_isolated_workspace
    workspace_packages = find_packages(context.source_space_abs, exclude_subspaces=True, warnings=[])
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 103, in find_packages
    raise RuntimeError('\n'.join(duplicates))
### RuntimeError: **Multiple packages found with the same name "uml_hri_nerve_pick_and_place":**
- armada_manipulation_old
- manipulation_experiments

**Comment by kyassini** [comment]
Hi, when I put this repo together it was based on the "uml_hri_nerve_pick_and_place" package (now located in the archived "armada_manipulation_old" repo). 
So if you want to have both packages in a workspace, one of them must be renamed and re-built by editing the package.xml, cmakelist, launch files, etc.

**Comment by decdox** [comment]
Thank you, kyassini. I fixed the error. 

BTW, it seems this project cannot implement simulation experiment separately, so should I connect to my real KINOVA Gen3 arm and run your script?

**Comment by kyassini** [comment]
You don't have to. I did my initial experiments only with the simulated Gen3 before using the real arm. 
You should be able use the [kortex_gazebo](https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel/kortex_gazebo) package and my code to run a simulation separately.

**Comment by decdox** [comment]
Sorry to bother again since i am new to grasping and kinova, so i want to use your code as a practice. The problem is that when i was doing the simulation experiment, no point clouds are detected. The following lines are after running _roslaunch uml_hri_nerve_pick_and_place gpd_grasping_node.launch_

> SUMMARY
> ========
> 
> PARAMETERS
>  * /detect_grasps/cloud_topic: /cloud_combined
>  * /detect_grasps/cloud_type: 0
>  * /detect_grasps/config_file: /usr/pkg/gpd/cfg/...
>  * /detect_grasps/rviz_topic: plot_grasps
>  * /detect_grasps/samples_topic: 
>  * /rosdistro: melodic
>  * /rosversion: 1.14.13
> 
> NODES
>   /
>     detect_grasps (gpd_ros/detect_grasps)
>   /my_gen3/
>     gpd_grasping_node (uml_hri_nerve_pick_and_place/gpd_grasping_node)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[detect_grasps-1]: started with pid [6061]
> process[my_gen3/gpd_grasping_node-2]: started with pid [6062]
> Init ....
> ============ HAND GEOMETRY ======================
> finger_width: 0.01
> hand_outer_diameter: 0.12
> hand_depth: 0.06
> hand_height: 0.02
> init_bite: 0.01
> =================================================
> ============ PLOTTING ========================
> plot_normals: false
> plot_samples false
> plot_candidates: false
> plot_filtered_candidates: false
> plot_valid_grasps: false
> plot_clustered_grasps: false
> plot_selected_grasps: true
> ==============================================
> ============ CLOUD PREPROCESSING =============
> voxelize: true
> voxel_size: 0.003
> remove_outliers: false
> workspace: -1.00 1.00 -1.00 1.00 -1.00 1.00 
> sample_above_plane: false
> normals_radius: 0.030
> refine_normals_k: 0
> ==============================================
> ============ CANDIDATE GENERATION ============
> num_samples: 500
> num_threads: 4
> nn_radius: 0.01
> hand axes: 2 
> num_orientations: 8
> num_finger_placements: 10
> deepen_hand: true
> friction_coeff: 20.00
> min_viable: 6
> ==============================================
> ============ GRASP IMAGE GEOMETRY ===============
> volume width: 0.1
> volume depth: 0.06
> volume height: 0.02
> image_size: 60
> image_num_channels: 15
> =================================================
> NET SETUP runtime: 0.0518186
> ============ CLASSIFIER ======================
> model_file: 
> weights_file: /usr/pkg/gpd/models/lenet/15channels/params/
> batch_size: 1
> ==============================================
> ============ CANDIDATE FILTERING =============
> candidate_workspace: -1.00 1.00 -1.00 1.00 -1.00 1.00 
> min_aperture: 0.0000
> max_aperture: 0.8500
> ==============================================
> ============ CLUSTERING ======================
> min_inliers: 1
> ==============================================
> 
> Created GPD ....
> [ INFO] [1664193704.706539525]: Waiting for point cloud to arrive ...
> [ INFO] [1664193705.868138145, 16.942000000]: Loading robot model 'gen3_robotiq_2f_85'...
> [ INFO] [1664193705.868590489, 16.942000000]: No root/virtual joint specified in SRDF. Assuming fixed joint
> [ INFO] [1664193706.960013416, 18.032000000]: Ready to take commands for planning group arm.
> [ WARN] [1664193706.960141650, 18.032000000]: Opening gripper...
> [ INFO] [1664193707.169979546, 18.242000000]: Moving to Top Position
> [ WARN] [1664193723.910559993, 34.962000000]: Top snapshot complete
**> [pcl::SampleConsensusModel::getSamples] Can not select 0 unique points out of 0!
> [pcl::RandomSampleConsensus::computeModel] No samples could be selected!
> [pcl::SACSegmentation::segment] Error segmenting the model! No solution found.**
> [ WARN] [1664193724.911908321, 35.962000000]: Publishing combined cloud...
> Failed to find match for field 'rgba'.
> [ INFO] [1664193724.919196316, 35.970000000]: Received cloud with 0 points.
> Processing cloud with 0 points.
> Voxelized cloud: 0
> Calculating surface normals ...
> num_threads: 4
**> [pcl::NormalEstimationOMP::compute] input_ is empty!**
>  runtime(computeNormals): 0.0000
> camera: 0, #indices: 0, #normals: 0 
> Calculated 0 surface normals in 0.0000s (mode: OpenMP).
> Reversing direction of normals that do not point to at least one camera ...
>  reversed 0 normals
>  runtime (reverse normals): 6.379e-06
> ERROR: Point cloud is empty![ INFO] [1664193724.929904259, 35.980000000]: Published 0 highest-scoring grasps.
> [ INFO] [1664193724.929942889, 35.980000000]: Waiting for point cloud to arrive ...
> [ WARN] [1664193724.929967853, 35.980000000]: Received Grasp Candidates
**> [my_gen3/gpd_grasping_node-2] process has died [pid 6062, exit code -11, cmd /home/zing/mealAssistiveRobot/grasp_ws/devel/lib/uml_hri_nerve_pick_and_place/gpd_grasping_node __name:=gpd_grasping_node __log:=/home/zing/.ros/log/ed4bc0ec-3d92-11ed-b620-b07b2523d886/my_gen3-gpd_grasping_node-2.log].
> log file: /home/zing/.ros/log/ed4bc0ec-3d92-11ed-b620-b07b2523d886/my_gen3-gpd_grasping_node-2*.log**
> 


The bold lines are the error messsges above.

Also, when i check perception in the rviz by running the perception.launch, there are no point clouds in the topic.
Thank you anyway!

**Comment by kyassini** [comment]
Just to make sure, are you placing an object in front of the arm in Gazebo and are you able to view the regular camera topics in RVIZ? If so, it might just be these workspace values that you need to change (or remove completely since the passthrough filter could be deleting all your points):
https://github.com/kyassini/manipulation_experiments/blob/287baa7767744cdfe966db02b3f5e203ca513980/src/functions/perception_class.cpp#L118-L151
